### ISSUE TITLE
couldn't find file 'jquery-ui/datepicker'

### ISSUE THREAD

**Issue by DanielKehoe** [opoloo/lines-engine#8]
I created a new Rails application using Ruby 2.4.0 and Rails 5.0.1:
```
$ rails new blogapp
```
and followed the install instructions (add lines gem, bundle, 'rails g lines:install', rake db:migrate). Then ran `rails server` and visited http://localhost:3000/blog.

Got the error:
```
Sprockets::FileNotFound in Lines::Articles#index
Showing /Users/danielkehoe/workspace/wip/blogapp/app/views/lines/articles/index.html.erb where line #2 raised:
couldn't find file 'jquery-ui/datepicker' with type 'application/javascript'
```

Disappointed to find the gem doesn't work on a simple install and the error hasn't been previously reported.

**Comment by DanielKehoe** [comment]
Apparently the error results from a recent upgrade of the gem `jquery-ui-rails` to 6.0.0.

The workaround is to lock the `jquery-ui-rails` gem. In your Gemfile, add:
```
# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails', '~> 5.0.5'
```

**Comment by simonneutert** [comment]
in lines-engine: admin.js 
datepicker is now in widgets sub:

//= require jquery-ui/widgets/datepicker

**Comment by edgarlepe** [comment]
Fixed with #9

**Comment by jamesosb** [comment]
Fresh install today and still receiving this error - couldn't find file 'jquery-ui/datepicker' with type 'application/javascript'. Any ideas?

**Comment by thebadmonkeydev** [comment]
I have this issue as well.  I've tested with the fork that @edgarlepe submitted with #9 and it works fine for me.  It would be nice if that could get reviewed/merged especially since the PR was opened back in February.

**Comment by ArisNance** [comment]
Hi all, 

I'm a bit new to rails and was wanting to give this gem a try. I'm currently having the same issue as noted above. @thebadmonkeydev @edgarlepe what exactly did you do to solve the problem? I appreciate any help/advice!

Thanks!

**Comment by edgarlepe** [comment]
Hi @ArisNance,
The fix has been merged, so make sure you're using version 1.2.3. If you're using rails, add `gem 'lines-engine', '1.2.3'` to your Gemfile.

**Comment by ArisNance** [comment]
Thanks for the reply @edgarlepe. I'm using the correct version of the gem and I am still having the same issue. Does any modifications need to happen in any of the asset files?


best,

**Comment by ArisNance** [comment]
@edgarlepe I was able to resolve the issue. It may of have something to do with the gem version, but it turned out to be the Lines assets folder. Once I reinstalled using -V 1.2.2.2 I deleted the whole Lines folder under assets and it seemed to work fine after that.


Thanks for all your help!!

**Comment by piyush8** [comment]
@ArisNance  Can you please elaborate bit more I am facing the same issue not bale to solve it 
Which gem verion -V 1.2.2.2?
From where you deleted the whole Lines folder under assets?

**Comment by ArisNance** [comment]
Hi @piyush8. Sorry for the late response. I don't remember the exact solution, but check out one of my old repos. It contains the fix to this problem. https://github.com/ArisNance/whereshara. Let me know if you resolve the problem. If not let me spin up my on env with your code and i'll debug it personally!

**Comment by piyush8** [comment]
Thanks for your reply @ArisNance I will check your repo and Let you know.

**Comment by piyush8** [comment]
I have gone through your github repo what ever I was missing I applied it in my project even I'm facing the same issue.
@ArisNance 
What would you suggest to do next?

**Comment by ArisNance** [comment]
Hey @piyush8 whats your hangouts? We could do a screenshare. Also please provide a link to your repo so I can verify its installed correctly and can troubleshoot from there before we chat.

**Comment by piyush8** [comment]
Hey my hangout id peyushchowhan7@gmail.com 
What time you will be free please inform me. I will be ready with the setup.
